theme: jekyll-theme-cayman
title: Machine Learning Study Notes
description: This is my personnel study notes. The materials can be from the most famous open courses, such as Andrew NG's ML, and deep learning, or from reference machine learnin books, or from the inverstigation of others people's notes, etc.
